### ISSUE TITLE
can't able to download pth model using git-lfs

### ISSUE THREAD

**Issue by lakshmanan1997** [nasir6/rPPG#1]
Git LFS: (0 of 0 files, 1 skipped) 0 B / 0 B, 83.27 MB skipped                 [f18ca579d42765d26bfdeb1a9833826a78ef42e61cb2974b6263c18d21fc8f84] Object does not exist on the server: [404] Object does not exist on the server
error: failed to fetch some objects from 'https://github.com/nasir6/rPPG.git/info/lfs'

**Comment by nasir6** [comment]
You can alternatively try to download it from google drive https://drive.google.com/open?id=1shRnrUAF5HyA_vwXJfCcrNVFkltT7U5E

**Comment by CangHaiQingYue** [comment]
Hi.
when i use git-lfs to clone ''linknet.pth', it said 'fatal: repository 'linknet.pth' dose not exist'.
ALso i can not visit ‘google drive’ for some reason。
Can you send this file to my e-mail: 921156593@qq.com
Thank you!
