### ISSUE TITLE
Could you please send me the pretrain model 'linknet.pth'?

### ISSUE THREAD

**Issue by anxiaoci** [nasir6/rPPG#15]
Sorry for asking this request. but I could't download  the pretrain model 'linknet.pth' from your  repository. If it's quite all right, please send this file to d202080766@hust.edu. Thanks very much.

**Comment by nasir6** [comment]
@anxiaoci it's shared through google drive you can try downloading it from [link](https://drive.google.com/open?id=1shRnrUAF5HyA_vwXJfCcrNVFkltT7U5E)
